### ISSUE TITLE
jobvite sync failing

### ISSUE THREAD

**Issue by jgmize** [mozmar/lumbergh#169]
quoth the log:
`Clock job job_syncjobvite@careers-stage: CRASHED: no element found: line 1, column 0`

This is affecting stage and prod.

**Comment by jgmize** [comment]
@glogiotatidis can you take a look at this?

**Comment by jgmize** [comment]
jobs are now reporting without any action on my part; leaving open for further investigation

**Comment by glogiotatidis** [comment]
That's jobvite returning empty responses and us not handling this safely. afiak changes are planned in lumbergh within the month which will fix this

**Comment by glogiotatidis** [comment]
As always thanks @jgmize for reporting :beers:

**Comment by glogiotatidis** [comment]
We're not using jobvite anymore, so it's safe to close this one.
